### ISSUE TITLE
no php files

### ISSUE THREAD

**Issue by melspence** [Apress/An-Introduction-to-PHP#2]
Guys

This sample zip appears to be for Mark's JavaScript for Web developers, though the images seem to be from the Down-Under site.

**Comment by manngo** [comment]
Absolutely correct. My mistake.

I have uploaded two files:

-	`sample.zip`: the source for the sample site.
-	`completed`: completed versions of the PHP files.

I have also updated the `README.md` file accordingly.

Note that the `sample.zip` file is _very_ large (about 30-odd Mb).

**Comment by manngo** [comment]
Do the new files solve the issue?

**Comment by melspence** [comment]
Yes it has, many thanks
