### ISSUE TITLE
URL in book is incorrect, missing 'An-'

### ISSUE THREAD

**Issue by chikega** [Apress/An-Introduction-to-PHP#3]
Under section "Web Server Setup", it reads:
"Download the sample site from `https://github.com/Apress/Introduction_to_PHP`. Unzip it and put it in a convenient location."

URL should be: https://github.com/Apress/An-Introduction-to-PHP
Essentially, the URL in the book is missing `An-`

**Comment by manngo** [comment]
> Under section "Web Server Setup", it reads: "Download the sample site from `https://github.com/Apress/Introduction_to_PHP`. Unzip it and put it in a convenient location."
> 
> URL should be: https://github.com/Apress/An-Introduction-to-PHP Essentially, the URL in the book is missing `An-`

The URL has now been changed to `https://github.com/Apress/Introduction-to-PHP`. Thanks for picking that up.

Let me know if that solves the problem.

**Comment by chikega** [comment]
Yep, that did the trick! Cheers!

**Comment by manngo** [comment]
> Yep, that did the trick! Cheers!

Excellent. Thanks.
