### ISSUE TITLE
Cloning or downloading as a zip results in corrupted completed and sample zip files

### ISSUE THREAD

**Issue by melspence** [Apress/An-Introduction-to-PHP#4]
Cloning or downloading as a zip results in corrupted completed and sample zip files

**Comment by manngo** [comment]
Thanks for your note.

It seems that GitHub does something weird with the Zip files, which I’m still trying to understand.

Meanwhile, I’ve updated the README file and added the files to a release.

Let me know how that works for you.

**Comment by melspence** [comment]
Now we are cooking with gas, all working, you can close the issue
Cheers
Mel

**Comment by manngo** [comment]
Great. Thanks.
